version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping Lambda code..."
      - zip function.zip lambda_function.py
  post_build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code \
          --function-name myLambda \
          --zip-file fileb://function.zip